"""
Train/Val/Test Split Generator
Author: Taradutt Pattnaik
Date: 2026

Description:
Creates train, val,test splits
for the DrugESP dataset using the MOSES split
mapping. The validation set is generated by randomly
sampling 10% of the MOSES training molecules.

Inputs:
- DrugESP_150k_compact.json
- DrugESP_150k_moses_mapping.json

Outputs:
- training_data/train.json
- training_data/val.json
- training_data/test.json

Split Strategy:
-MOSES official train/test split is preserved
- Validation set sampled from MOSES training molecules
- Random seed 42 reproducibility

"""

import json
import numpy as np
from pathlib import Path

BASE = Path.cwd()

# Load compact dataset
print("Loading dataset...")
with open(BASE / 'DrugESP_150k_compact.json') as f:
    dataset = json.load(f)


print(f"Loaded {len(dataset):,} molecules")

#Load MOSES mapping for train/test split
with open(BASE / 'DrugESP_150k_moses_mapping.json') as f:
    mapping = json.load(f)

split_lookup = {
    m['mol_id']: m['moses_split']
    for m in mapping
}

# Split the  dataset
train = [
    m for m in dataset
    if split_lookup.get(m['mol_id']) == 'train'
]

test = [
    m for m in dataset
    if split_lookup.get(m['mol_id']) == 'test'
]

# Stable ordering to ensuure reproducibility
train.sort(key=lambda x: x['mol_id'])

# Create validation set from train (10% of train)
np.random.seed(42)


n_val = int(len(train) * 0.1)

val_idx = set(
    np.random.choice(len(train), n_val, replace=False)
)

val = [
    m for i, m in enumerate(train)
    if i in val_idx
]

train = [
    m for i, m in enumerate(train)
    if i not in val_idx
]

# Integrity checks
train_ids = {m['mol_id'] for m in train}
val_ids   = {m['mol_id'] for m in val}
test_ids  = {m['mol_id'] for m in test}

assert train_ids.isdisjoint(val_ids)
assert train_ids.isdisjoint(test_ids)
assert val_ids.isdisjoint(test_ids)

total = len(train) + len(val) + len(test)
assert total == len(dataset)

# Summary
print("\nSplit:")
print(f"  Train: {len(train):,}  (MOSES train - 10% val)")
print(f"  Val:   {len(val):,}   (10% of MOSES train)")
print(f"  Test:  {len(test):,}  (MOSES test split)")

# Save the newly createdsplits
TRAIN_DIR = BASE / 'training_data'
TRAIN_DIR.mkdir(exist_ok=True)

for name, split in [('train', train),
                    ('val', val),
                    ('test', test)]:

    out = TRAIN_DIR / f'{name}.json'

    with open(out, 'w') as f:
        json.dump(split, f)

    print(f"Saved {name}.json — {len(split):,} molecules")

print("\nDataset splitting complete.")
